/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search.
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggregationSortInnerValue {
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<String>,
}

impl AggregationSortInnerValue {
    pub fn new() -> AggregationSortInnerValue {
        AggregationSortInnerValue { order: None }
    }
}
