/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search.
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// Aggregation : Aggregation Alias

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Aggregation {
    #[serde(rename = "terms", skip_serializing_if = "Option::is_none")]
    pub terms: Option<Box<crate::models::AggregationTerms>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort:
        Option<Vec<::std::collections::HashMap<String, crate::models::AggregationSortInnerValue>>>,
}

impl Aggregation {
    /// Aggregation Alias
    pub fn new() -> Aggregation {
        Aggregation {
            terms: None,
            sort: None,
        }
    }
}
