/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search.
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// Aggregation : Query aggregation object

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Aggregation {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl Aggregation {
    /// Query aggregation object
    pub fn new(name: String, field: String) -> Aggregation {
        Aggregation {
            name,
            field,
            size: None,
        }
    }
}
