/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search.
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// BoolFilter : Boolean attribute filter

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoolFilter {
    #[serde(rename = "should", skip_serializing_if = "Option::is_none")]
    pub should: Option<Vec<serde_json::Value>>,
    #[serde(rename = "must", skip_serializing_if = "Option::is_none")]
    pub must: Option<Vec<serde_json::Value>>,
    #[serde(rename = "must_not", skip_serializing_if = "Option::is_none")]
    pub must_not: Option<Vec<serde_json::Value>>,
}

impl BoolFilter {
    /// Boolean attribute filter
    pub fn new() -> BoolFilter {
        BoolFilter {
            should: None,
            must: None,
            must_not: None,
        }
    }
}
