/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search.
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// ErrorResponse : Error response

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "error")]
    pub error: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "status")]
    pub status: i32,
}

impl ErrorResponse {
    /// Error response
    pub fn new(
        error: ::std::collections::HashMap<String, serde_json::Value>,
        status: i32,
    ) -> ErrorResponse {
        ErrorResponse { error, status }
    }
}
