/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// Facet : Query FACET expression



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Facet {
    /// The name of an attribute to facet
    #[serde(rename = "attr")]
    pub attr: String,
    /// Facet alias
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    /// The number of facet values to return
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl Facet {
    /// Query FACET expression
    pub fn new(attr: String) -> Facet {
        Facet {
            attr,
            alias: None,
            limit: None,
        }
    }
}


