/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// GeoDistanceFilterLocationAnchor : Geo pin point object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoDistanceFilterLocationAnchor {
    /// Geo latitude of pin point in degrees
    #[serde(rename = "lat", skip_serializing_if = "Option::is_none")]
    pub lat: Option<f32>,
    /// Geo longitude pf pin point in degrees
    #[serde(rename = "lon", skip_serializing_if = "Option::is_none")]
    pub lon: Option<f32>,
}

impl GeoDistanceFilterLocationAnchor {
    /// Geo pin point object
    pub fn new() -> GeoDistanceFilterLocationAnchor {
        GeoDistanceFilterLocationAnchor {
            lat: None,
            lon: None,
        }
    }
}


