/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// MatchFilter : Query match filter



#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct MatchFilter {
    #[serde(rename = "query_string")]
    pub query_string: String,
    #[serde(rename = "query_fields")]
    pub query_fields: String,
}

impl MatchFilter {
    /// Query match filter
    pub fn new(query_string: String, query_fields: String) -> MatchFilter {
        MatchFilter {
            query_string,
            query_fields,
        }
    }
}


