/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// NotFilterBoolean : Query filter



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFilterBoolean {
    #[serde(rename = "filter_field")]
    pub filter_field: String,
    #[serde(rename = "operation")]
    pub operation: String,
    #[serde(rename = "filter_value")]
    pub filter_value: bool,
}

impl NotFilterBoolean {
    /// Query filter
    pub fn new(filter_field: String, operation: String, filter_value: bool) -> NotFilterBoolean {
        NotFilterBoolean {
            filter_field,
            operation,
            filter_value,
        }
    }
}


