/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search.
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// QueryFilter : Query string filter

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFilter {
    #[serde(rename = "query_string")]
    pub query_string: String,
}

impl QueryFilter {
    /// Query string filter
    pub fn new(query_string: String) -> QueryFilter {
        QueryFilter { query_string }
    }
}
