/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// SortMultiple : Query sort expression for multiple attributes



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortMultiple {
    #[serde(rename = "attrs")]
    pub attrs: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "replace")]
    pub replace: bool,
}

impl SortMultiple {
    /// Query sort expression for multiple attributes
    pub fn new(attrs: ::std::collections::HashMap<String, serde_json::Value>, replace: bool) -> SortMultiple {
        SortMultiple {
            attrs,
            replace,
        }
    }
}


