/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// SortOrder : Query sort expression



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortOrder {
    #[serde(rename = "attr")]
    pub attr: String,
    #[serde(rename = "order")]
    pub order: Order,
}

impl SortOrder {
    /// Query sort expression
    pub fn new(attr: String, order: Order) -> SortOrder {
        SortOrder {
            attr,
            order,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Order {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

impl Default for Order {
    fn default() -> Order {
        Self::Asc
    }
}

