/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search.
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateResponse : Success response

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateResponse {
    #[serde(rename = "_index", skip_serializing_if = "Option::is_none")]
    pub _index: Option<String>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<i32>,
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<i64>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl UpdateResponse {
    /// Success response
    pub fn new() -> UpdateResponse {
        UpdateResponse {
            _index: None,
            updated: None,
            _id: None,
            result: None,
        }
    }
}
